# syntax = docker/dockerfile:experimental

ARG PHP_VERSION=8.2
ARG NODE_VERSION=18
FROM ubuntu:22.04 AS app

ARG PHP_VERSION
ENV DEBIAN_FRONTEND=noninteractive \
    COMPOSER_ALLOW_SUPERUSER=1 \
    COMPOSER_HOME=/composer \
    COMPOSER_MAX_PARALLEL_HTTP=24 \
    PHP_DATE_TIMEZONE=UTC \
    PHP_DISPLAY_ERRORS=Off \
    PHP_ERROR_REPORTING=22527 \
    PHP_MEMORY_LIMIT=256M \
    PHP_MAX_EXECUTION_TIME=90 \
    PHP_POST_MAX_SIZE=100M \
    PHP_UPLOAD_MAX_FILE_SIZE=100M \
    PHP_ALLOW_URL_FOPEN=Off \
    QA_SERVER=apache-mod-php \
    QA_PHP_VERSION=${PHP_VERSION} \
    AIKIDO_BLOCKING=true \
    AIKIDO_BLOCK=true \
    AIKIDO_DISK_LOGS=true \
    AIKIDO_DEBUG=true

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer
COPY .fly/php/ondrej_ubuntu_php.gpg /etc/apt/trusted.gpg.d/ondrej_ubuntu_php.gpg
ADD .fly/php/packages/${PHP_VERSION}.txt /tmp/php-packages.txt

RUN apt-get update \
    && apt-get install -y --no-install-recommends gnupg2 ca-certificates git-core curl zip unzip \
        rsync vim-tiny htop sqlite3 apache2 cron python3-flask procps tini \
    && ln -sf /usr/bin/vim.tiny /etc/alternatives/vim \
    && ln -sf /etc/alternatives/vim /usr/bin/vim \
    && echo "deb http://ppa.launchpad.net/ondrej/php/ubuntu jammy main" > /etc/apt/sources.list.d/ondrej-ubuntu-php-focal.list \
    && apt-get update \
    && sed -i "/php${PHP_VERSION}-fpm/d" /tmp/php-packages.txt \
    && apt-get -y --no-install-recommends install $(cat /tmp/php-packages.txt) libapache2-mod-php${PHP_VERSION} \
    && a2enmod rewrite headers php${PHP_VERSION} \
    && a2dissite 000-default \
    && mkdir -p /var/www/html/public \
    && echo "index" > /var/www/html/public/index.php \
    && echo "ServerName localhost" >> /etc/apache2/apache2.conf \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*

COPY .qa-control-tests/apache-mod-php/apache.conf /etc/apache2/sites-available/laravel.conf
COPY .qa-control-tests/apache-mod-php/ports.conf /etc/apache2/ports.conf
COPY .qa-control-tests/common/control_server.py /usr/local/bin/control-server
COPY .qa-control-tests/common/entrypoint.sh /qa-entrypoint
RUN chmod 755 /usr/local/bin/control-server /qa-entrypoint \
    && a2ensite laravel

COPY . /var/www/html
WORKDIR /var/www/html

RUN composer install --optimize-autoloader --no-dev \
    && mkdir -p storage/logs \
    && php artisan optimize:clear \
    && chown -R www-data:www-data /var/www/html \
    && echo "MAILTO=\"\"\n* * * * * www-data /usr/bin/php /var/www/html/artisan schedule:run" > /etc/cron.d/laravel \
    && sed -i='' '/->withMiddleware(function (Middleware \$middleware) {/a\
        \$middleware->trustProxies(at: "*");\
    ' bootstrap/app.php; \
    rm -rf /var/www/html/.qa-control-tests

FROM node:${NODE_VERSION} AS assets

WORKDIR /app
COPY . .
COPY --from=app /var/www/html/vendor /app/vendor
RUN if [ -f "vite.config.js" ]; then \
        ASSET_CMD="build"; \
    else \
        ASSET_CMD="production"; \
    fi; \
    if [ -f "yarn.lock" ]; then \
        yarn install --frozen-lockfile; \
        yarn $ASSET_CMD; \
    elif [ -f "pnpm-lock.yaml" ]; then \
        corepack enable && corepack prepare pnpm@latest-8 --activate; \
        pnpm install --frozen-lockfile; \
        pnpm run $ASSET_CMD; \
    elif [ -f "package-lock.json" ]; then \
        npm ci --no-audit; \
        npm run $ASSET_CMD; \
    else \
        npm install; \
        npm run $ASSET_CMD; \
    fi

FROM app

COPY --from=assets /app/public /var/www/html/public-npm
RUN rsync -ar /var/www/html/public-npm/ /var/www/html/public/ \
    && rm -rf /var/www/html/public-npm \
    && chown -R www-data:www-data /var/www/html/public

EXPOSE 8080 8081
ENTRYPOINT ["/usr/bin/tini", "--", "/qa-entrypoint"]
